//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------
namespace AQUACORE_CMPG223
{
    public partial class VisitorRestaurantOrder
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.TextBox txtTable;
        protected global::System.Web.UI.WebControls.TextBox txtQuantity;
        protected global::System.Web.UI.WebControls.CheckBoxList cblFooditems;
        protected global::System.Web.UI.WebControls.Button btnPlaceOrder;
        protected global::System.Web.UI.WebControls.Button btnMyOrders;
        protected global::System.Web.UI.WebControls.Button btnBack;
        protected global::System.Web.UI.WebControls.Label lblMsg;
    }
}